use-grammars = { only = ["go", "gomod", "gosum", "gowork", "markdown", "html", "css", "javascript", "typescript", "tsx"] }

[language-server.gopls.config]
buildFlags = ["-tags=component,integration,production,wireinject,acceptance,oidc"]
completeUnimported = true

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]

[[language]]
name = "markdown"
soft-wrap.enable = true

[[language]]
name = "html"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["vscode-css-language-server"]

[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["typescript-language-server"]
